version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ADMIN_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d

  database_migrations:
    build: ./python_services/database_migrations
    container_name: database_migrations
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - default

  backend:
    build: ./back
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      database_migrations:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    networks:
      - default

  news_parser:
    build: ./python_services/news_parser
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      database_migrations:
        condition: service_completed_successfully
    networks:
      - default

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  redis_data: