/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Получить новости
         * @description Возвращает список новостей за указанный период для пользователя
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewsRequest"];
                };
            };
            responses: {
                /** @description Успешный ответ со списком новостей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewsResponse"];
                    };
                };
                /** @description Ошибка валидации входных данных */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Получить сводку новости
         * @description Возвращает полную сводку конкретной новости
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SummaryRequest"];
                };
            };
            responses: {
                /** @description Успешный ответ со сводкой новости */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SummaryResponse"];
                    };
                };
                /** @description Ошибка валидации входных данных */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация пользователя
         * @description Регистрирует нового пользователя и возвращает токен
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
            responses: {
                /** @description Успешная регистрация */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Ошибка валидации входных данных */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Авторизация пользователя
         * @description Авторизует пользователя и возвращает токен
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            responses: {
                /** @description Успешная авторизация */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Ошибка валидации входных данных */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Register: {
            /** @description имя пользователя */
            name: string;
            /** @description Список тегов предпочтений */
            preferences: string[];
        };
        Login: {
            /** @description имя пользователя */
            name: string;
        };
        TokenResponse: {
            /** @description JWT-токен для авторизации */
            access_token: string;
        };
        /**
         * @description Период за который нужно получить сводку новостей
         * @enum {string}
         */
        NewsPeriod: "day" | "week" | "month";
        NewsRequest: {
            /** @description id пользователя */
            user_id: number;
            news_period: components["schemas"]["NewsPeriod"];
        };
        News: {
            /** @description id новости */
            news_id: number;
            /** @description Ссылка на картинку новости */
            img_url: string;
            /** @description Заголовок новости */
            header: string;
            /** @description Краткое описание новости */
            mini_description: string;
        };
        NewsResponse: {
            /** @description Список новостей */
            news: components["schemas"]["News"][];
        };
        SummaryRequest: {
            /** @description id новости */
            news_id: number;
        };
        SummaryResponse: {
            /** @description Заголовок новости */
            header: string;
            /** @description Сводка новости */
            summary: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
